execute-glpk:
	glpsol -m set_part.mod -d dat/delta.dat -o sol/delta.sol --tmlim 5400 --log log/delta.log;
	glpsol -m set_part.mod -d dat/heart.dat -o sol/heart.sol --tmlim 5400 --log log/heart.log;
	glpsol -m set_part.mod -d dat/meteor.dat -o sol/meteor.sol --tmlim 5400 --log log/meteor.log;
	glpsol -m set_part.mod -d dat/sppnw05.dat -o sol/sppnw05.sol --tmlim 5400 --log log/sppnw05.log;
	glpsol -m set_part.mod -d dat/sppnw16.dat -o sol/sppnw16.sol --tmlim 5400 --log log/sppnw16.log;
	glpsol -m set_part.mod -d dat/sppnw32.dat -o sol/sppnw32.sol --tmlim 5400 --log log/sppnw32.log;
	glpsol -m set_part.mod -d dat/sppnw34.dat -o sol/sppnw34.sol --tmlim 5400 --log log/sppnw34.log;
	glpsol -m set_part.mod -d dat/sppnw36.dat -o sol/sppnw36.sol --tmlim 5400 --log log/sppnw36.log;
	glpsol -m set_part.mod -d dat/sppnw41.dat -o sol/sppnw41.sol --tmlim 5400 --log log/sppnw41.log;
	glpsol -m set_part.mod -d dat/sppaa06.dat -o sol/sppaa06.sol --tmlim 5400 --log log/sppaa06.log;
	glpsol -m set_part.mod -d dat/sppus01.dat -o sol/sppus01.sol --tmlim 5400 --log log/sppus01.log		
